const ACTION_TYPE_TOGGLE_WORD = "TOGGLE_WORD"
const ACTION_TYPE_REMOVE_WORD = "REMOVEWORD"
const ACTION_TYPE_TOGGLE_FORM = "TOGGLEFORM"
const ACTION_TYPE_ADD_WORD = "ADDWORD"
const ACTION_TYPE_FILTER_MODE = "FILTERMODE"





export default { ACTION_TYPE_TOGGLE_WORD, ACTION_TYPE_FILTER_MODE, ACTION_TYPE_ADD_WORD, ACTION_TYPE_TOGGLE_FORM, ACTION_TYPE_REMOVE_WORD };